test: \
	../../Linear_List/src/sequenticl_list.c \
	../../Other_Linear_Structure/src/sequential_queue.c \
	sort.h \
	heap_sort.c \
	merge_sort.c \
	radix_sort.c \
	shell_sort.c \
	bubble_sort.c \
	insertion_sort.c \
	quick_sort.c \
	selection_sort.c \
	test.c
	gcc $^ -g

clean:
	rm -rf ./a.out *.o *.gch a.out.dSYM

.PHONY: clean test
